kumuluzee:
  name: ai
  env:
    name: test
  version: 1.0.0
  server:
    http:
      port: 8082
  #datasources:
  #  - jndi-name: jdbc/ImageMetadataDS
  #    connection-url: jdbc:postgresql://192.168.29.109:5432/image-metadata
  #    username: dbuser
  #    password: postgres
  #    max-pool-size: 20
  #config:
  #  etcd:
  #    hosts: http://34.89.142.186:2379
  discovery:
    etcd:
      hosts: http://34.89.142.186:2379/
  health:
    logs:
      enabled: true
    checks:
      etcd-health-check:
        connection-url: http://34.89.142.186:2379/health
  metrics:
    web-instrumentation:
      - name: ai-api
        url-pattern: /ai/api/*
configuration-properties:
  ai:
    enabled: true